layout_spectrum: 1
typography_spectrum: 0.2755102
color:
  saturation: 0.3904404
  lightness: 0.5225564
  brandStrength: 0.5032223
  rhythmicContrast: 0.8147153
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: 'N'
